name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denzuko/dps-meta@v1
        with:
          type: lisp-actor
